In [70]:
import pandas as pd
import numpy as np

import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

## DATA PREPARATION

In [71]:
data = 'https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv'

In [72]:
df = pd.read_csv(data)
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [73]:
df = df[['engine_displacement', 'horsepower', 'vehicle_weight', 'model_year', 'fuel_efficiency_mpg']]
df

,engine_displacement,horsepower,vehicle_weight,model_year,fuel_efficiency_mpg
0,2180,243.0,3870,2006,31.9
1,2390,272.0,4210,2008,31.3
2,2320,267.0,4240,1996,27.5
3,2130,258.0,4490,1989,28.5
4,2580,304.0,4510,1994,31.0
...,...,...,...,...,...
9995,2470,271.0,4690,2005,27.4
9996,2300,244.0,4370,1993,30.0
9997,2480,267.0,4590,2014,28.1
9998,2180,270.0,4450,2004,32.2
9999,2380,295.0,4370,2011,30.2

## Question 1

In [74]:
df.isnull().sum()

engine_displacement      0
horsepower             877
vehicle_weight           0
model_year               0
fuel_efficiency_mpg      0
dtype: int64

## Question 2

In [75]:
df['horsepower'].median()

np.float64(254.0)

Prepare n split the dataset

In [76]:
n = len(df)
n_val = int(n * 0.2)
n_test = int(n * 0.2)
n_train = n - n_val - n_test
n

10000

In [77]:
n_val, n_test, n_train

(2000, 2000, 6000)

In [78]:
np.random.seed(42)
idx = np.arange(n)
np.random.shuffle(idx)

In [79]:
df_train = df.iloc[idx[:n_train]]
df_val = df.iloc[idx[n_train:n_train + n_val]]
df_test = df.iloc[idx[n_train + n_val:]]

In [80]:
df_train

,engine_displacement,horsepower,vehicle_weight,model_year,fuel_efficiency_mpg
6252,1900,239.0,3790,2015,32.5
4684,2000,224.0,4380,1992,29.1
1731,2330,286.0,4090,2022,34.1
4742,2300,NaN,4150,1997,30.6
4521,2340,269.0,4400,2001,30.7
...,...,...,...,...,...
7895,2280,242.0,4590,2018,29.8
9590,2300,NaN,4240,1984,25.1
7288,2240,255.0,4190,1989,27.7
278,2430,254.0,4280,2020,31.6
3252,2390,266.0,4220,1996,28.0

In [81]:
df_val

,engine_displacement,horsepower,vehicle_weight,model_year,fuel_efficiency_mpg
2480,2240,265.0,3990,2004,30.4
289,2390,259.0,4770,2019,32.8
6086,2360,265.0,4320,2018,27.8
3075,2430,279.0,4430,2008,28.6
8123,2220,249.0,4030,1999,31.1
...,...,...,...,...,...
1638,1980,229.0,4140,2020,30.3
5891,2590,263.0,4630,1989,28.7
7427,2390,264.0,4550,2017,30.6
608,2330,244.0,4440,2014,31.0
6907,2170,260.0,4460,2021,30.8

In [82]:
df_test

,engine_displacement,horsepower,vehicle_weight,model_year,fuel_efficiency_mpg
399,2370,268.0,4410,1981,27.8
7247,2240,256.0,4220,2020,37.3
6406,2090,217.0,3910,2023,33.1
882,2280,251.0,4420,2021,31.3
3565,2450,256.0,4420,1979,26.4
...,...,...,...,...,...
5734,2100,257.0,4130,1988,30.7
5191,2160,231.0,4180,2000,25.5
5390,2430,246.0,4660,2013,30.1
860,2450,307.0,4500,2014,30.5
7270,2060,273.0,3960,1997,34.9

## Question 3

In [83]:
y_train = df_train['fuel_efficiency_mpg'].values
y_val = df_val['fuel_efficiency_mpg'].values

In [84]:
df_train = df_train.drop(columns=['fuel_efficiency_mpg'])
df_val = df_val.drop(columns=['fuel_efficiency_mpg'])

In [85]:
def train_linear_regression(X, y):
    ones = np.ones(X.shape[0])
    X = np.column_stack([ones, X])
    
    XTX = X.T.dot(X)
    XTX_inv = np.linalg.inv(XTX)
    w = XTX_inv.dot(X.T).dot(y)
    
    return w[0], w[1:]

In [86]:
def rmse(y, y_pred):
    error = y_pred - y
    mse = (error ** 2).mean()
    return np.sqrt(mse)

with 0

In [87]:
X_train_0 = df_train.fillna(0).values
X_val_0 = df_val.fillna(0).values

In [88]:
w0, w = train_linear_regression(X_train_0, y_train)

In [89]:
y_pred_0 = w0 + X_val_0.dot(w)

In [90]:
score_0 = round(rmse(y_val, y_pred_0), 3)
round(score_0, 3)

np.float64(2.205)

with mean

In [91]:
mean_hp = df_train['horsepower'].mean()

In [92]:
X_train_mean = df_train.fillna(mean_hp).values
X_val_mean = df_val.fillna(mean_hp).values

In [93]:
w0, w = train_linear_regression(X_train_mean, y_train)

In [94]:
y_pred_mean = w0 + X_val_mean.dot(w)

In [95]:
score_mean = round(rmse(y_val, y_pred_mean), 3)
round(score_mean, 3)

np.float64(2.202)

## Question 4

In [96]:
X_train = df_train.fillna(0).values
X_val = df_val.fillna(0).values

In [97]:
def train_linear_regression_reg(x, y, r):
    ones = np.ones(x.shape[0])
    X = np.column_stack([ones, x])

    XTX = X.T.dot(X)
    XTX = XTX + r * np.eye(XTX.shape[0])

    XTX_inv = np.linalg.inv(XTX)
    w_full = XTX_inv.dot(X.T).dot(y)

    return w_full[0], w_full[1:]

In [98]:
for r in [0, 0.01, 0.1, 1, 5, 10, 100]:
    w0, w = train_linear_regression_reg(X_train, y_train, r=r)
    
    y_pred = w0 + X_val.dot(w)
    score = round(rmse(y_val, y_pred), 4)
    print(r, w0, score)

0 -153.8849618823138 2.2053
0.01 -148.3092124404723 2.2058
0.1 -111.83871039306318 2.2241
1 -32.331865964971264 2.3492
5 -7.7728522099734025 2.4094
10 -3.9871164160193766 2.4195
100 -0.40821964884790385 2.4292

## Question 5

In [107]:
scores = []

for s in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]:
    np.random.seed(s)
    idx = np.arange(n)
    np.random.shuffle(idx)
    
    df_train_s = df.iloc[idx[:n_train]].copy()
    df_val_s = df.iloc[idx[n_train:n_train + n_val]].copy()
    
    y_train_s = df_train_s['fuel_efficiency_mpg'].values
    y_val_s = df_val_s['fuel_efficiency_mpg'].values
    
    X_train_s = df_train_s.drop(columns=['fuel_efficiency_mpg']).fillna(0).values
    X_val_s = df_val_s.drop(columns=['fuel_efficiency_mpg']).fillna(0).values
    
    w0, w = train_linear_regression(X_train_s, y_train_s)
    y_pred_s = w0 + X_val_s.dot(w)
    score = rmse(y_val_s, y_pred_s)
    
    scores.append(score)

round(np.std(scores), 3)

np.float64(0.029)

## Question 6

In [108]:
np.random.seed(9)
idx = np.arange(n)
np.random.shuffle(idx)

df_train = df.iloc[idx[:n_train]].copy()
df_val = df.iloc[idx[n_train:n_train + n_val]].copy()
df_test = df.iloc[idx[n_train + n_val:]].copy()

In [109]:
df_full_train = pd.concat([df_train, df_val]).reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [110]:
y_full_train = df_full_train['fuel_efficiency_mpg'].values
y_test = df_test['fuel_efficiency_mpg'].values

X_full_train = df_full_train.drop(columns=['fuel_efficiency_mpg']).fillna(0).values
X_test = df_test.drop(columns=['fuel_efficiency_mpg']).fillna(0).values

In [111]:
w0, w = train_linear_regression_reg(X_full_train, y_full_train, r=0.001)

y_pred = w0 + X_test.dot(w)

score_test = round(rmse(y_test, y_pred), 3)
score_test

np.float64(2.236)